Загрузка библиотек

In [11]:
import os
import sys
import pandas as pd
import numpy as np
import datetime
from matplotlib import pyplot as plt
import seaborn as sns
from IPython.display import display, Markdown


from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import f1_score
from sklearn import model_selection, linear_model, metrics
from sklearn.model_selection import GridSearchCV
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor

plt.rcParams.update({'figure.max_open_warning': 0})
%matplotlib inline

import warnings
warnings.filterwarnings("ignore")

from sklearn.metrics import classification_report, confusion_matrix, f1_score, precision_score, recall_score

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LinearRegression,Lasso, Ridge, SGDRegressor
from sklearn.ensemble import IsolationForest
from sklearn.svm import OneClassSVM, SVR
from sklearn.neighbors import KNeighborsRegressor

import pickle

Загрузка данных

In [19]:
path = r"C:/Users/user/Desktop/test.pkl/test.pkl"
with open(path, "rb") as f:
    list_of_df = pickle.load(f)

In [21]:
len(list_of_df)

34

In [22]:
pd.concat(list_of_df)

,Accelerometer1RMS,Accelerometer2RMS,Current,Pressure,Temperature,Thermocouple,Voltage,Volume Flow RateRMS
datetime,,,,,,,,
2020-03-09 12:14:36,0.027429,0.040353,0.770310,0.382638,71.2129,25.0827,219.789,32.0000
2020-03-09 12:14:37,0.027269,0.040226,1.096960,0.710565,71.4284,25.0863,233.117,32.0104
2020-03-09 12:14:38,0.027040,0.039773,1.140150,0.054711,71.3468,25.0874,234.745,32.0000
2020-03-09 12:14:39,0.027563,0.040313,1.108680,-0.273216,71.3258,25.0897,205.254,32.0104
2020-03-09 12:14:41,0.026570,0.039566,0.704404,0.382638,71.2725,25.0831,212.095,33.0000
...,...,...,...,...,...,...,...,...
2020-03-09 11:34:30,0.027081,0.038897,0.624425,0.054711,71.3921,25.4292,232.531,32.0000
2020-03-09 11:34:31,0.026692,0.039526,0.663211,0.382638,71.3944,25.4293,234.818,32.0057
2020-03-09 11:34:32,0.026836,0.039188,0.771298,0.054711,71.4257,25.4274,230.235,32.9891
2020-03-09 11:34:34,0.027231,0.040847,0.699393,0.054711,71.1430,25.4226,250.675,31.0116
2020-03-09 11:34:35,0.026347,0.039156,1.002360,0.054711,71.4900,25.4243,235.976,32.9945